# This is a basic workflow to help you get started with Actions

name: CI-CD #(nome do workflow)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch - definição dos eventos que irão startar o workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab - Permite a execução manual do workflow, usado quando for melhorando a pipline.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI: #esse é um job, o build.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest #agente que irá rodar o job, neste caso o S.O

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 #pega o codigo do projeto no reposítorio
      - name: build and push a Docker images  #nome a action
        uses: docker/build-push-action@v2.6.1  #modelo de action utilizado (olhar marketplace ao lado)
        with: #determina os parametros que será urtilizado
          context: /home/murilo/aulasDocker/projetKubeDev/aula2/rotten-potatoes/src #path que será enviado ao docker deamon para criar a imagem
          file: /home/murilo/aulasDocker/projetKubeDev/aula2/rotten-potatoes/src/DockerFile
          push: true
          tags: | #usado o pip para colocar em baixo. Para gerar um número automático de versão, utiliza-se a variável ${{ github.run_number }} , ou seja número exclusivo para cada execução de um fluxo de trabalho específico em um repositório
            murilogomes/rotten-potatoes:latest
            murilogomes/rotten-potatoes: ${{ github.run_number }} 
            
